/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ganatsiozWEB1.glb --transform 
Files: ganatsiozWEB1.glb [37.87MB] > ganatsiozWEB1-transformed.glb [5.8MB] (85%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ganatsiozWEB1-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="WEB">
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/ganatsiozWEB1-transformed.glb')
